<a href="https://colab.research.google.com/github/AdelineKwakye/walmart-huricane-project/blob/main/notebooks/scratch/Amilyn_Estes_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
!git clone https://github.com/AdelineKwakye/walmart-huricane-project.git
%cd /content/walmart-huricane-project
!ls
!git pull

fatal: destination path 'walmart-huricane-project' already exists and is not an empty directory.
/content/walmart-huricane-project
CHARTER.md  data  notebooks  README.md
Already up to date.

In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import requests

In [11]:
transactions = pd.read_csv("walmart-huricane-project/data/walmart_transactions.csv")
stores = pd.read_csv("walmart-huricane-project/data/store_locations.csv")

print("TRANSACTION COLUMNS:")
print(transactions.columns.tolist())

print("\nSTORE COLUMNS:")
print(stores.columns.tolist())

display(transactions.head())
display(stores.head())

TRANSACTION COLUMNS:
['transaction_id', 'store_id', 'timestamp', 'sku', 'product_name', 'category', 'quantity', 'unit_price']

STORE COLUMNS:
['store_id', 'store_name', 'city', 'state', 'zip_code', 'latitude', 'longitude', 'region']

,transaction_id,store_id,timestamp,sku,product_name,category,quantity,unit_price
0,TXN012636,FL-710,2024-09-24T09:48:13,PNUTBTR-16,PEANUT BUTTER,Grocery,1,3.15
1,TXN000759,fl-412,2024-09-13 20:30:20,CNSOUP-01,CANNED SOUP,GROCERY,1,2.02
2,TXN003338,FL-105,2024-09-17 10:06:00,TOILETPAPER12,Toilet Paper 12-Roll,Household Essentials,2,10.47
3,TXN025020,FL-330,2024-09-11 06:29:08,ROKU-STD,Roku Streaming Stick,ELECTRONICS,1,28.59
4,TXN015797,FL-302,2024-09-26 15:59:42,BEER-24,Light Beer 24pk,Alcoholic Beverages,3,18.82

,store_id,store_name,city,state,zip_code,latitude,longitude,region
0,FL-239,Walmart Supercenter Orlando,Orlando,FL,32801,28.5383,-81.3792,Central
1,FL-105,Walmart Supercenter Tampa,Tampa,FL,33602,27.9506,-82.4572,West
2,FL-330,Walmart Supercenter Miami,Miami,FL,33101,25.7617,-80.1918,South
3,FL-412,Walmart Supercenter Jacksonville,Jacksonville,FL,32099,30.3322,-81.6557,North
4,FL-287,Walmart Neighborhood Market Kissimmee,Kissimmee,Florida,34741,28.2920,-81.4076,Central